# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-17 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20171201_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='alt_tag',
            field=models.CharField(default='undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='Category', max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='metatags',
            field=models.CharField(default='undefined', max_length=1000),
        ),
        migrations.AlterField(
            model_name='click',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='alt_tag1',
            field=models.CharField(default='undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='alt_tag2',
            field=models.CharField(default='undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='alt_tag3',
            field=models.CharField(default='undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='alt_tag4',
            field=models.CharField(default='undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='home_image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='home_image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='home_image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='home_image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
