# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-03-17 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0033_auto_20171201_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='alt_tag',
            field=models.CharField(default='undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(default='Company', max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='metatags',
            field=models.CharField(default='undefined', max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='page_description',
            field=models.CharField(default='undefined', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
